/// This file contains (theoretically) autogenerated code. It should not be edited manually.
import DependencyKit
import Foundation

extension Requirements where I: NetworkMonitorInterfaceDependency {
    var networkMonitor: NetworkMonitorInterface? { injected.networkMonitor }
}


public typealias _NetworkClientRequirements = NilDependency
