/// This file contains (theoretically) autogenerated code. It should not be edited manually.
import DependencyKit
import Foundation
import NetworkClient

extension Dependency where T:DIAppName {
    var appName: String { dependency.appName }
}
extension Dependency where T:DIBoolIndicator {
    var boolIndicator: Bool { dependency.boolIndicator }
}
extension Dependency where T:DICurrentTime {
    var currentTime: Date { dependency.currentTime }
}
extension Dependency where T:DIMessage {
    var messageToCarryThrough: String { dependency.messageToCarryThrough }
}
extension Dependency where T:DINetworkClient {
    var networkClient: NetworkClient { dependency.networkClient }
}
extension Dependency where T:DISessionToken {
    var sessionToken: String? { dependency.sessionToken }
}
extension Dependency where T:DIStartupTime {
    var startupTime: Date { dependency.startupTime }
}

protocol DependencyFill {
    typealias LevelOne = Empty & DIStartupTime & DIMessage
    typealias LevelTwo = Empty & DIStartupTime & DICurrentTime & DIMessage & DINetworkClient
    typealias LevelThree = Empty & DISessionToken & DIAppName & DIStartupTime & DICurrentTime & DIBoolIndicator & DINetworkClient
}
