/// This file contains (theoretically) autogenerated code. It should not be edited manually.
import DependencyKit
import Foundation
import NetworkClient

extension Dependency where T:DIAppName {
    var appName: String { dependency.appName }
}
extension Dependency where T:DIBoolIndicator {
    var boolIndicator: Bool { dependency.boolIndicator }
}
extension Dependency where T:DICurrentTime {
    var currentTime: Date { dependency.currentTime }
}
extension Dependency where T:DIMessage {
    var messageToCarryThrough: String { dependency.messageToCarryThrough }
}
extension Dependency where T:DINetworkClient {
    var networkClient: NetworkClient { dependency.networkClient }
}
extension Dependency where T:DISessionToken {
    var sessionToken: String? { dependency.sessionToken }
}
extension Dependency where T:DIStartupTime {
    var startupTime: Date { dependency.startupTime }
}

protocol DependencyFill {
    typealias LevelOneDependency = Empty & DIStartupTime & DIMessage
    typealias LevelTwoDependency = Empty & DIStartupTime & DICurrentTime & DIMessage & DINetworkClient
    typealias LevelThreeDependency = Empty & DISessionToken & DIAppName & DIStartupTime & DICurrentTime & DIBoolIndicator & DINetworkClient
}

extension Dependency {
    typealias LevelOneDependency = Dependency & DependencyFill.LevelOneDependency
    typealias LevelTwoDependency = Dependency & DependencyFill.LevelTwoDependency
    typealias LevelThreeDependency = Dependency & DependencyFill.LevelThreeDependency
}

extension LevelOneComponent: DependencyFill.LevelOneDependency {}
extension LevelTwoComponent: DependencyFill.LevelTwoDependency {}
extension LevelThreeComponent: DependencyFill.LevelThreeDependency {}
