/// This file contains (theoretically) autogenerated code. It should not be edited manually. 
import Foundation

extension Dependency where T: DIRootName {
    var rootName: String { dependency.rootName }
}
extension Dependency where T: DIName {
    var name: String { dependency.name }
}
extension Dependency where T: DIStartupTime {
    var startupTime: Date { dependency.startupTime }
}
extension Dependency where T: DIMood {
    var mood: Bool { dependency.mood }
}
extension Dependency where T: DIFinalThoughts {
    var finalThoughts: String { dependency.finalThoughts }
}

protocol DependencyFill {
    typealias Root = Empty & DIStartupTime & DIFinalThoughts
    typealias LevelOne = Empty & DIStartupTime & DIFinalThoughts
    typealias LevelTwo = Empty & DIFinalThoughts
    typealias LevelThree = Empty
}

extension DependencyBase {
    typealias Root = Dependency & DependencyFill.Root
    typealias LevelOne = Dependency & DependencyFill.LevelOne
    typealias LevelTwo = Dependency & DependencyFill.LevelTwo
    typealias LevelThree = Dependency & DependencyFill.LevelThree
}

extension RootComponent: DependencyFill.Root {}
extension LevelOneComponent: DependencyFill.LevelOne {}
extension LevelTwoComponent: DependencyFill.LevelTwo {}
extension LevelThreeComponent: DependencyFill.LevelThree {}
